In [4]:
import numpy as np
rand_array = np.random.randint(1,100,(10,3))
print(rand_array)

[[69 63 52]
 [32 57 15]
 [74 67 52]
 [95 60 87]
 [ 9 83 92]
 [22 97 67]
 [92 22 96]
 [59 49 95]
 [65 44 56]
 [67 93 13]]
